// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: iyarkov/kit/object.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectStatus int32

const (
	ObjectStatus_pending ObjectStatus = 0
	ObjectStatus_active  ObjectStatus = 1
	ObjectStatus_deleted ObjectStatus = 2
	ObjectStatus_purged  ObjectStatus = 3
)

// Enum value maps for ObjectStatus.
var (
	ObjectStatus_name = map[int32]string{
		0: "pending",
		1: "active",
		2: "deleted",
		3: "purged",
	}
	ObjectStatus_value = map[string]int32{
		"pending": 0,
		"active":  1,
		"deleted": 2,
		"purged":  3,
	}
)

func (x ObjectStatus) Enum() *ObjectStatus {
	p := new(ObjectStatus)
	*p = x
	return p
}

func (x ObjectStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_iyarkov_kit_object_proto_enumTypes[0].Descriptor()
}

func (ObjectStatus) Type() protoreflect.EnumType {
	return &file_iyarkov_kit_object_proto_enumTypes[0]
}

func (x ObjectStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectStatus.Descriptor instead.
func (ObjectStatus) EnumDescriptor() ([]byte, []int) {
	return file_iyarkov_kit_object_proto_rawDescGZIP(), []int{0}
}

type ObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ObjectRequest) Reset() {
	*x = ObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iyarkov_kit_object_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRequest) ProtoMessage() {}

func (x *ObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iyarkov_kit_object_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRequest.ProtoReflect.Descriptor instead.
func (*ObjectRequest) Descriptor() ([]byte, []int) {
	return file_iyarkov_kit_object_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_iyarkov_kit_object_proto protoreflect.FileDescriptor

var file_iyarkov_kit_object_proto_rawDesc = []byte{
	0x0a, 0x18, 0x69, 0x79, 0x61, 0x72, 0x6b, 0x6f, 0x76, 0x2f, 0x6b, 0x69, 0x74, 0x2f, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x69, 0x79, 0x61, 0x72,
	0x6b, 0x6f, 0x76, 0x2e, 0x6b, 0x69, 0x74, 0x22, 0x1f, 0x0a, 0x0d, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x2a, 0x40, 0x0a, 0x0c, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x70, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0a,
	0x0a, 0x06, 0x70, 0x75, 0x72, 0x67, 0x65, 0x64, 0x10, 0x03, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x79, 0x61, 0x72, 0x6b, 0x6f, 0x76,
	0x2f, 0x6b, 0x69, 0x74, 0x2f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_iyarkov_kit_object_proto_rawDescOnce sync.Once
	file_iyarkov_kit_object_proto_rawDescData = file_iyarkov_kit_object_proto_rawDesc
)

func file_iyarkov_kit_object_proto_rawDescGZIP() []byte {
	file_iyarkov_kit_object_proto_rawDescOnce.Do(func() {
		file_iyarkov_kit_object_proto_rawDescData = protoimpl.X.CompressGZIP(file_iyarkov_kit_object_proto_rawDescData)
	})
	return file_iyarkov_kit_object_proto_rawDescData
}

var file_iyarkov_kit_object_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_iyarkov_kit_object_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_iyarkov_kit_object_proto_goTypes = []interface{}{
	(ObjectStatus)(0),     // 0: iyarkov.kit.ObjectStatus
	(*ObjectRequest)(nil), // 1: iyarkov.kit.ObjectRequest
}
var file_iyarkov_kit_object_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_iyarkov_kit_object_proto_init() }
func file_iyarkov_kit_object_proto_init() {
	if File_iyarkov_kit_object_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_iyarkov_kit_object_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_iyarkov_kit_object_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iyarkov_kit_object_proto_goTypes,
		DependencyIndexes: file_iyarkov_kit_object_proto_depIdxs,
		EnumInfos:         file_iyarkov_kit_object_proto_enumTypes,
		MessageInfos:      file_iyarkov_kit_object_proto_msgTypes,
	}.Build()
	File_iyarkov_kit_object_proto = out.File
	file_iyarkov_kit_object_proto_rawDesc = nil
	file_iyarkov_kit_object_proto_goTypes = nil
	file_iyarkov_kit_object_proto_depIdxs = nil
}
