// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: iyarkov/kit/page_request.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortOrder int32

const (
	SortOrder_asc  SortOrder = 0
	SortOrder_desc SortOrder = 1
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "asc",
		1: "desc",
	}
	SortOrder_value = map[string]int32{
		"asc":  0,
		"desc": 1,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_iyarkov_kit_page_request_proto_enumTypes[0].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_iyarkov_kit_page_request_proto_enumTypes[0]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_iyarkov_kit_page_request_proto_rawDescGZIP(), []int{0}
}

type PageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter    string    `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Sort      string    `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	Direction SortOrder `protobuf:"varint,3,opt,name=direction,proto3,enum=iyarkov.kit.SortOrder" json:"direction,omitempty"`
	Offset    string    `protobuf:"bytes,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit     uint32    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Fields    []string  `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iyarkov_kit_page_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iyarkov_kit_page_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_iyarkov_kit_page_request_proto_rawDescGZIP(), []int{0}
}

func (x *PageRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *PageRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *PageRequest) GetDirection() SortOrder {
	if x != nil {
		return x.Direction
	}
	return SortOrder_asc
}

func (x *PageRequest) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

func (x *PageRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PageRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_iyarkov_kit_page_request_proto protoreflect.FileDescriptor

var file_iyarkov_kit_page_request_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x69, 0x79, 0x61, 0x72, 0x6b, 0x6f, 0x76, 0x2f, 0x6b, 0x69, 0x74, 0x2f, 0x70, 0x61,
	0x67, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x69, 0x79, 0x61, 0x72, 0x6b, 0x6f, 0x76, 0x2e, 0x6b, 0x69, 0x74, 0x22, 0xb5, 0x01,
	0x0a, 0x0b, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x34, 0x0a, 0x09, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x69,
	0x79, 0x61, 0x72, 0x6b, 0x6f, 0x76, 0x2e, 0x6b, 0x69, 0x74, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x2a, 0x1e, 0x0a, 0x09, 0x53, 0x6f, 0x72, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x07, 0x0a, 0x03, 0x61, 0x73, 0x63, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x64,
	0x65, 0x73, 0x63, 0x10, 0x01, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x79, 0x61, 0x72, 0x6b, 0x6f, 0x76, 0x2f, 0x6b, 0x69, 0x74, 0x2f,
	0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_iyarkov_kit_page_request_proto_rawDescOnce sync.Once
	file_iyarkov_kit_page_request_proto_rawDescData = file_iyarkov_kit_page_request_proto_rawDesc
)

func file_iyarkov_kit_page_request_proto_rawDescGZIP() []byte {
	file_iyarkov_kit_page_request_proto_rawDescOnce.Do(func() {
		file_iyarkov_kit_page_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_iyarkov_kit_page_request_proto_rawDescData)
	})
	return file_iyarkov_kit_page_request_proto_rawDescData
}

var file_iyarkov_kit_page_request_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_iyarkov_kit_page_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_iyarkov_kit_page_request_proto_goTypes = []interface{}{
	(SortOrder)(0),      // 0: iyarkov.kit.SortOrder
	(*PageRequest)(nil), // 1: iyarkov.kit.PageRequest
}
var file_iyarkov_kit_page_request_proto_depIdxs = []int32{
	0, // 0: iyarkov.kit.PageRequest.direction:type_name -> iyarkov.kit.SortOrder
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_iyarkov_kit_page_request_proto_init() }
func file_iyarkov_kit_page_request_proto_init() {
	if File_iyarkov_kit_page_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_iyarkov_kit_page_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_iyarkov_kit_page_request_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iyarkov_kit_page_request_proto_goTypes,
		DependencyIndexes: file_iyarkov_kit_page_request_proto_depIdxs,
		EnumInfos:         file_iyarkov_kit_page_request_proto_enumTypes,
		MessageInfos:      file_iyarkov_kit_page_request_proto_msgTypes,
	}.Build()
	File_iyarkov_kit_page_request_proto = out.File
	file_iyarkov_kit_page_request_proto_rawDesc = nil
	file_iyarkov_kit_page_request_proto_goTypes = nil
	file_iyarkov_kit_page_request_proto_depIdxs = nil
}
